### ISSUE TITLE
System.OutOfMemoryException: Array dimensions exceeded supported range.

### ISSUE THREAD

**Issue by manaphoenix** [Goz3rr/SatisfactorySaveEditor#196]
Attempted to open save and this happened. Given it says out of memory I'm adding that I have 16Gb of RAM :)

[log.txt](https://github.com/Goz3rr/SatisfactorySaveEditor/files/5263817/log.txt)

[SchematicFix.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/5263826/SchematicFix.zip)

**Comment by Ryder17z** [comment]
> 2020-09-23 20:40:37.7286 - INFO: Opening save file: E:\MyDownloads\SchematicFix.zip
2020-09-23 20:40:47.1812 - ERROR: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at SatisfactorySaveParser.BinaryIOExtensions.ReadCharArray(BinaryReader reader)
   at SatisfactorySaveParser.BinaryIOExtensions.ReadLengthPrefixedString(BinaryReader reader)
   at SatisfactorySaveParser.Save.FSaveHeader.Parse(BinaryReader reader)
   at SatisfactorySaveParser.SatisfactorySave..ctor(String file)
   at SatisfactorySaveEditor.ViewModel.MainViewModel.LoadFileAsync(String path)
EXCEPTION: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at SatisfactorySaveParser.BinaryIOExtensions.ReadCharArray(BinaryReader reader)
   at SatisfactorySaveParser.BinaryIOExtensions.ReadLengthPrefixedString(BinaryReader reader)
   at SatisfactorySaveParser.Save.FSaveHeader.Parse(BinaryReader reader)
   at SatisfactorySaveParser.SatisfactorySave..ctor(String file)
   at SatisfactorySaveEditor.ViewModel.MainViewModel.LoadFileAsync(String path)


This is on a 32GB pc.

**Comment by Goz3rr** [comment]
Thanks for the report, this is fixed in the 0.9.10 release
