### ISSUE TITLE
I cant open experimental  update 6

### ISSUE THREAD

**Issue by ultra0violet** [Goz3rr/SatisfactorySaveEditor#251]

**Comment by SolomonCM** [comment]
program throws an exception when a save from update 6 is opened. error: SatisfactorySaveParser.Exception.UnnownBuildVersionException
log file attached. hope the program is updated for update 6 very soon. much prefer it over the calculator site

**Comment by Chariot-Rider** [comment]
I have the same issue, here is my log file for reference

2022-06-19 21:44:33.6496 - INFO: Opening save file: C:\Users\MYDRIVE\AppData\Local\FactoryGame\Saved\SaveGames\76561199214759584\First of many_autosave_1.sav
2022-06-19 21:44:33.8077 - DEBUG: Read save header: HeaderVersion=UE426EngineUpdate, SaveVersion=29, BuildVersion=192921, MapName=Persistent_Level, MapOpts=?startloc=Grass Fields?skiponboarding?sessionName=First of many?Visibility=SV_FriendsOnly, Session=First of many, PlayTime=3102701, SaveTime=637912682383320000
2022-06-19 21:44:46.7983 - ERROR: SatisfactorySaveParser.Exceptions.UnknownBuildVersionException: Exception of type 'SatisfactorySaveParser.Exceptions.UnknownBuildVersionException' was thrown.
   at SatisfactorySaveParser.Save.FSaveHeader.Parse(BinaryReader reader)
   at SatisfactorySaveParser.SatisfactorySave..ctor(String file)
   at SatisfactorySaveEditor.ViewModel.MainViewModel.LoadFileAsync(String path)
EXCEPTION: SatisfactorySaveParser.Exceptions.UnknownBuildVersionException: Exception of type 'SatisfactorySaveParser.Exceptions.UnknownBuildVersionException' was thrown.
   at SatisfactorySaveParser.Save.FSaveHeader.Parse(BinaryReader reader)
   at SatisfactorySaveParser.SatisfactorySave..ctor(String file)
   at SatisfactorySaveEditor.ViewModel.MainViewModel.LoadFileAsync(String path)

**Comment by Kadigan** [comment]
That's probably because it hasn't been updated to support U6 yet - the last commit was on April 1st, and U6 came out June 14th. I'm given to understand that U6 uses a different saving scheme, so this editor likely won't work with it until it's been updated to support that save scheme.

**Comment by Chariot-Rider** [comment]
Thanks for your input, I am aware that is the issue. 

The new save routine will be implemented in future updates, as per the release notes. Thus, implementing an update to the save editor could benefit the user population; unless the plan is to only support the early access releases, which is fine.

**Comment by Goz3rr** [comment]
I hope to get to it soon, if some of you could upload some example saves for testing that'd be great

**Comment by MinerPL** [comment]
Example of an empty save from the latest experimental version
[ExampleSave.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/8960853/ExampleSave.zip)

**Comment by Chariot-Rider** [comment]
Save game after deploying the hub
[Experimental_autosave_0.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/8973411/Experimental_autosave_0.zip)

**Comment by LarsWesselius** [comment]
I had a look, looks like the save format is quite a bit different from what it was. It now starts with some length prefixed strings that I don't know if they mean anything. Data seems to start at offset 252 now (0xFC). If I seek to that before saved entities loop then it'll read them but fail at the next asserts.
My knowledge of the save format (and how you even figure out such a thing, let me know!) is too little to continue but hopefully this is helpful to at least someone..

**Comment by netcore-kushal** [comment]
@Goz3rr - Eagerly awaiting the new version :D
When will you able to release new version with update 6 support? Can you tell us tentative date or month?

**Comment by ThomasGP** [comment]
I created a pull request (#262) for update 6 read support. I still hope that the original authors implement full support, so this hopefully is a start.

For those unable to compile the code: I created [a release with my "fork"](https://github.com/ThomasGP/SatisfactorySaveEditor/releases/tag/v0.10.2-with-update-6-read-support), just unzip it like the releases here.

NOTE: this release only has read support and I only tested it with my savefile. You cannot save files, only load them in the editor, if they are from the current game version. I want to leave this to the original authors.

**Comment by jgillip** [comment]
> I created a pull request (#262) for update 6 read support. I still hope that the original authors implement full support, so this could be a start.
> 
> For those unable to compile the code: I created [a release with my "fork"](https://github.com/ThomasGP/SatisfactorySaveEditor/releases/tag/v0.10.2-with-update-6-read-support), just unzip it like the releases here.
> 
> NOTE: this release only has read support and I only tested it with my savefile. You cannot save files, only load them in the editor, if they are from the current game version. I want to leave this to the original authors.

Nice great work, I tried to modify the code myself for a fix but I didn't understand the structure well enough.

**Comment by Chariot-Rider** [comment]
I conclude that Goz3rr has given up on this project. Considering this update has now been superseded by Satisfactory 7. This brilliant tool is now dead 💀
