### ISSUE TITLE
Error opening file

### ISSUE THREAD

**Issue by araggedierhurt** [Goz3rr/SatisfactorySaveEditor#259]
2022-09-23 09:59:38.4180 - INFO: Opening save file: C:\Users\Steve\AppData\Local\FactoryGame\Saved\SaveGames\76561197975424853\Final Factory.sav
2022-09-23 09:59:38.4370 - DEBUG: Read save header: HeaderVersion=VersionPlusOne, SaveVersion=30, BuildVersion=201717, MapName=Persistent_Level, MapOpts=?startloc=DuneDesert?skiponboarding?sessionName=Final Factory?Visibility=SV_Private, Session=Final Factory, PlayTime=14267, SaveTime=637995015298630000
2022-09-23 09:59:41.9505 - ERROR: SatisfactorySaveParser.Exceptions.UnknownSaveVersionException: Exception of type 'SatisfactorySaveParser.Exceptions.UnknownSaveVersionException' was thrown.
   at SatisfactorySaveParser.Save.FSaveHeader.Parse(BinaryReader reader)
   at SatisfactorySaveParser.SatisfactorySave..ctor(String file)
   at SatisfactorySaveEditor.ViewModel.MainViewModel.LoadFileAsync(String path)
EXCEPTION: SatisfactorySaveParser.Exceptions.UnknownSaveVersionException: Exception of type 'SatisfactorySaveParser.Exceptions.UnknownSaveVersionException' was thrown.
   at SatisfactorySaveParser.Save.FSaveHeader.Parse(BinaryReader reader)
   at SatisfactorySaveParser.SatisfactorySave..ctor(String file)
   at SatisfactorySaveEditor.ViewModel.MainViewModel.LoadFileAsync(String path)

**Comment by AMeierDev** [comment]
I have the same issue after updating to Satisfactory Update 6.

**Comment by Pandapip1** [comment]
Same here. To avoid polluting the comment history, I recommend that if you have the same issue, just react :+1: to the original issue.
