### ISSUE TITLE
Not Loading Save When Game Closed

### ISSUE THREAD

**Issue by TesterOfDoom** [Goz3rr/SatisfactorySaveEditor#260]
Here Is The Log 

2022-10-14 13:02:07.0755 - INFO: Opening save file: C:\Users\RandomNameHere\AppData\Local\FactoryGame\Saved\SaveGames\76561199027831137\Unnamed_141022-130033.sav
2022-10-14 13:02:07.0945 - DEBUG: Read save header: HeaderVersion=VersionPlusOne, SaveVersion=30, BuildVersion=202470, MapName=Persistent_Level, MapOpts=?startloc=DuneDesert?skiponboarding?sessionName=Game Test?Visibility=SV_Private, Session=Game Test, PlayTime=6, SaveTime=638013744333590000
2022-10-14 13:02:13.0590 - ERROR: SatisfactorySaveParser.Exceptions.UnknownSaveVersionException: Exception of type 'SatisfactorySaveParser.Exceptions.UnknownSaveVersionException' was thrown.
   at SatisfactorySaveParser.Save.FSaveHeader.Parse(BinaryReader reader)
   at SatisfactorySaveParser.SatisfactorySave..ctor(String file)
   at SatisfactorySaveEditor.ViewModel.MainViewModel.LoadFileAsync(String path)
EXCEPTION: SatisfactorySaveParser.Exceptions.UnknownSaveVersionException: Exception of type 'SatisfactorySaveParser.Exceptions.UnknownSaveVersionException' was thrown.
   at SatisfactorySaveParser.Save.FSaveHeader.Parse(BinaryReader reader)
   at SatisfactorySaveParser.SatisfactorySave..ctor(String file)
   at SatisfactorySaveEditor.ViewModel.MainViewModel.LoadFileAsync(String path)

Can You Help Me With It? Im Runing Update 6 With No Mods

**Comment by ZZWolf47** [comment]
I have the same issue

**Comment by Ajajane** [comment]
Same exact issue here, running update 6, but also using mods.

**Comment by budak7273** [comment]
More info in #267
